/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "pcomet"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "pcomet"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.1"
#endif

enum enum_extrinsic { extrinsic__NULL = -1, extrinsic_arg_all = 0, extrinsic_arg_f1m, extrinsic_arg_nvd, extrinsic_arg_index};
enum enum_intrinsic { intrinsic__NULL = -1, intrinsic_arg_all = 0 };

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  short num_arg;	/**< @brief the number of threads to be used. (default='1').  */
  char * num_orig;	/**< @brief the number of threads to be used. original value given at command line.  */
  const char *num_help; /**< @brief the number of threads to be used. help description.  */
  short cpufreq_arg;	/**< @brief CPU frequency to measure timing of the metrics, MHz (can be fetched by `$ lscpu`). (default='2100').  */
  char * cpufreq_orig;	/**< @brief CPU frequency to measure timing of the metrics, MHz (can be fetched by `$ lscpu`). original value given at command line.  */
  const char *cpufreq_help; /**< @brief CPU frequency to measure timing of the metrics, MHz (can be fetched by `$ lscpu`). help description.  */
  enum enum_extrinsic extrinsic_arg;	/**< @brief extrinsic quality metrics to be evaluated (default='all').  */
  char * extrinsic_orig;	/**< @brief extrinsic quality metrics to be evaluated original value given at command line.  */
  const char *extrinsic_help; /**< @brief extrinsic quality metrics to be evaluated help description.  */
  enum enum_intrinsic intrinsic_arg;	/**< @brief intrinsic quality metrics to be evaluated (default='all').  */
  char * intrinsic_orig;	/**< @brief intrinsic quality metrics to be evaluated original value given at command line.  */
  const char *intrinsic_help; /**< @brief intrinsic quality metrics to be evaluated help description.  */
  int weighted_flag;	/**< @brief the input network is weighted (default=off).  */
  const char *weighted_help; /**< @brief the input network is weighted help description.  */
  int directed_flag;	/**< @brief the input network is directed (default=off).  */
  const char *directed_help; /**< @brief the input network is directed help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int num_given ;	/**< @brief Whether num was given.  */
  unsigned int cpufreq_given ;	/**< @brief Whether cpufreq was given.  */
  unsigned int extrinsic_given ;	/**< @brief Whether extrinsic was given.  */
  unsigned int intrinsic_given ;	/**< @brief Whether intrinsic was given.  */
  unsigned int weighted_given ;	/**< @brief Whether weighted was given.  */
  unsigned int directed_given ;	/**< @brief Whether directed was given.  */

  char **inputs ; /**< @brief unamed options (options without names) */
  unsigned inputs_num ; /**< @brief unamed options number */
  int gr_metrics_group_counter; /**< @brief Counter for group gr_metrics */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);

extern const char *cmdline_parser_extrinsic_values[];  /**< @brief Possible values for extrinsic. */
extern const char *cmdline_parser_intrinsic_values[];  /**< @brief Possible values for intrinsic. */


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
